# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c40e7bf14439979938c8b758234eb26dfecf6c46d21a53be80cf7ac584e144599271bfb32dbbc2daa6691a9bb0508545ba5c29c887313ba91209a5fc97a67661

test:
  secret_key_base: 3493cf285fa0080171e3287e64c33a33a881436557dd02091c9e1797e487ec0e88d64bb55875e824a57f30fadf76b6fca5b7ffcea5a4671d41608354aa59224d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
